### ISSUE TITLE
Issues not visible or editable

### ISSUE THREAD

**Issue by TheRealWaldo** [forkhubs/android#609] opened 2014-12-11 16:37 UTC
On android 4.4.4 on a samsung galaxy note 4, issues are not visible from the issue dashboard or from a repository view when clicking on a specific issue.

**Comment by grahamlyons** [comment] 2015-01-05 23:31
I'm also seeing blank issue pages with the app from the Play store on the latest Android on Nexus 4.

**Comment by dcharles525** [comment] 2015-01-06 00:11
Yeah a lot of the pages come up blank as @grahamlyons has said, I think a release should happen sooner then later, this issue has affected me for over a month on all of my android devices.

**Comment by HolgerJeromin** [comment] 2015-01-06 08:40
+1 for release an update for the main problems. Tweaking and optimising (appcompat) could be done later IMO.

**Comment by jmanuel1** [comment] 2015-01-11 09:20
I also have @audricd's issue on my Nexus 5 (Android 5.0.1).

**Comment by sedrubal** [comment] 2015-01-17 12:33
Same on nexus 5 omnirom 4.4

Why aren't there any updates in PlayStore or f-droid? The provided version is published since almost a year.

**Comment by zhaofengli** [comment] 2015-01-19 10:13
Confirmed that this bug is also present in the HEAD version of the app (Nexus 4 with CM12/Android 5.0.2).

**Comment by longshiptech** [comment] 2015-01-27 22:16
Seeing the same on HTC One M8 running Across Android 4.4.4

**Comment by longshiptech** [comment] 2015-01-27 22:23
As noted above, installing Forkhub from the Play Store solves the issue. Is there a PR to merge from the forked repo?

**Comment by TheRealWaldo** [comment] 2015-01-27 23:46
It does not solve all related issues.  Issue dashboard remains empty.

**Comment by MRJpcHUT** [comment] 2015-02-14 12:08
@jonqnp. I agree 100%. I'm just beginning as a Dev, but usability should take priority (clean code, fallback functions, and at very least, an "O-Shit" button to report serious bugs. It's all about usability, otherwise, we might as well develop a firewall (not the scope)

-mrj

**Comment by MRJpcHUT** [comment] 2015-02-14 12:10
@jonanp excuse the typo please. This is why native UX should be prio. #correctifwrong

**Comment by hzsweers** [comment] 2015-04-23 11:27
These seem to be working fine for me

![2015-04-23 04 26 59](https://cloud.githubusercontent.com/assets/1361086/7296058/038220a0-e971-11e4-958c-f67bdd0d0950.png)

**Comment by ogregoire** [comment] 2015-07-25 13:09
Well, it's not working well for me.
![screenshot_2015-07-25-15-05-33](https://cloud.githubusercontent.com/assets/666970/8889555/0176ed2e-32df-11e5-9018-6d529c7813f6.png)

**Comment by hzsweers** [comment] 2015-07-25 18:43
We need way more information in order to do anything. Have you tried the
latest master? Does it happen on other repos? What happens if you log out
and then back in?

**Comment by hzsweers** [comment] 2015-07-25 22:14
@ogregoire that comment doesn't really help us solve the problem. We need more details information from users. Does it work on latest master?

**Comment by ogregoire** [comment] 2015-07-25 22:40
Tbh, I just got bored of that issue and I wanted to do my job by reporting the bug so I found this page. As I saw that no screenshots of the application with the blank screen and the last update was a "works well for me" with a screenshot, I put a screenshot showing it doesn't work.

And by that, I mean of course the latest published version on the play store has this screen (the official GitHub app, which seems to have been pulled from the store now that I check).

So if you have an application on the store, which one is it? I'll test that one first. If it still doesn't work, please tell me the steps to compile and install the latest version from the master branch: I'm a desktop developer, not a mobile one (I never even installed something outside the store).

**Comment by hzsweers** [comment] 2015-07-25 22:43
Please read the README, we explain all the GitHub story there. As for building, just clone it and run `./gradlew installDebug` with your phone connected in USB debugging mode. You'll have to uninstall your current version though, as we have the same package name at the momemt.

**Comment by ogregoire** [comment] 2015-07-27 00:27
I'm writing this comment from the app. This means that it works OK with the ForkHub version.

**Comment by hzsweers** [comment] 2015-07-27 03:45
Good to hear, closing this for now then

**Closed by hzsweers** 2015-07-27 03:45 UTC
Labels: Needs more info
